# URL
BASE_URL = "https://api.fireworks.ai/inference/v1"

# Models
EMBEDDING_MODEL = "nomic-ai/nomic-embed-text-v1.5"
INFERENCE_MODEL = "mistralai/Mistral-7B-Instruct-v0.3"

# Keys
EMBEDDING_API_KEY = ""
INFERENCE_API_KEY = ""
